version: '3'
services:
  mediawiki:
    image: issafalcon/mediawiki:1.39
    restart: always
    ports:
      - 8090:80
    volumes:
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./images:/var/www/html/images
  database:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./databases/MediaWiki:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      # Defaults for clean install
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
  parsoid:
    image: issafalcon/parsoid:0.11
    ports:
      - 8091:8000
    environment:
      - PARSOID_DOMAIN_mediawiki=http://mediawiki/api.php
